### ISSUE TITLE
shapes are not equal with FakeTensor

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#1078]
### 🐛 Describe the bug

Run TestFakeTensor with xpu we got a lot of errors of shapes are not equal. For example:

======================================================================
ERROR: test_fake_crossref_backward_amp_nn_functional_multilabel_soft_margin_loss_xpu_float32 (__main__.TestFakeTensorXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniforge3/envs/daisy_upstream/lib/python3.10/site-packages/torch/_subclasses/fake_utils.py", line 182, in __torch_dispatch__
    torch._prims.utils.compare_tensor_meta(
  File "/home/gta/miniforge3/envs/daisy_upstream/lib/python3.10/site-packages/torch/_prims_common/__init__.py", line 156, in compare_tensor_meta
    raise AssertionError(msg)
AssertionError: Shapes torch.Size([0]) and torch.Size([5]) are not equal!

Another issue is in backward:
======================================================================
ERROR: test_fake_crossref_backward_amp_nn_functional_multilabel_soft_margin_loss_xpu_float32 (__main__.TestFakeTensorXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniforge3/envs/daisy_upstream/lib/python3.10/site-packages/torch/_subclasses/fake_utils.py", line 182, in __torch_dispatch__
    torch._prims.utils.compare_tensor_meta(
  File "/home/gta/miniforge3/envs/daisy_upstream/lib/python3.10/site-packages/torch/_prims_common/__init__.py", line 156, in compare_tensor_meta
    raise AssertionError(msg)
AssertionError: Shapes torch.Size([0]) and torch.Size([5]) are not equal!

To reproduce, change test/test_ops.py instantiate_device_type_tests(TestFakeTensor, globals()) ==> instantiate_device_type_tests(TestFakeTensor, globals(), allow_xpu=True) and run
```
PYTORCH_TEST_WITH_SLOW=1 python  test_ops.py -k TestTags
```

### Versions

latest version

**Comment by chunhuanMeng** [comment]
The results for real tensors are aligned with CUDA, but not for fake tensors. The root cause is that there is some CUDA specific codes in aten::log_sigmoid_forward.
ref:https://github.com/pytorch/pytorch/blob/main/torch/_decomp/decompositions.py#L2803
So we need raise a pr to stock pytorch.

**Comment by chunhuanMeng** [comment]
pr link:https://github.com/pytorch/pytorch/pull/141333

**Comment by Stonepia** [comment]
close as completed
