### ISSUE TITLE
LNL Windows got unexpected error message

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#1171]
### 🐛 Describe the bug

On LNL Windows with 1202 nightly wheel we got this error. No such problem on linux.

__________________________ TestPoolingNNDeviceTypeXPU.test_MaxUnpool_index_errors_case2_xpu ___________________________
Traceback (most recent call last):
  File "c:\Users\dcai01\pytorch\third_party\torch-xpu-ops\test\xpu\nn\test_pooling_xpu.py", line 313, in _test_MaxUnpool_index_errors
    self.assertIn(error_msg, output, "The expected error was not found")
  File "C:\Users\dcai01\.conda\envs\daisy\lib\unittest\case.py", line 1112, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\dcai01\.conda\envs\daisy\lib\unittest\case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: 'Assertion `maxind >= 0 && maxind < outputImageSize` failed' not found in '\nAssertHandler::printMessage\n' : The expected error was not found

To execute this test, run the following from the base repo dir:
    python test\nn\test_pooling.py TestPoolingNNDeviceTypeXPU.test_MaxUnpool_index_errors_case2_xpu

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
------------------------------------------------ Captured stdout call -------------------------------------------------
####  Assertion `maxind >= 0 && maxind < outputImageSize` failed
AssertHandler::printMessage

=============================================== short test summary info ===============================================
FAILED nn\test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_MaxUnpool_index_errors_case2_xpu - AssertionError: 'Assertion `maxind >= 0 && maxind < outputImageSize` failed' not found in '\nAssertHandler::printMe...
========================================= 1 failed, 132 deselected in 10.05s ==========================================

### Versions

20241202 wheel.

**Comment by Stonepia** [comment]
Currently this is skipped in Windows CI. We need an update of this.

**Comment by gaopengff** [comment]
This seems a compiler issue. We already tracked this on jira **PYTORCHDGQ-5888**

**Comment by libohao1201** [comment]
Verified with pt28, this issue still exists.
```
(pt28_rc1) C:\pt28_rc1\pytorch\third_party\torch-xpu-ops\test\xpu>pytest -v nn\test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_MaxUnpool_index_errors_case2_xpu
================================================= test session starts =================================================
platform win32 -- Python 3.10.18, pytest-7.3.2, pluggy-1.6.0 -- C:\Users\kf01\miniforge-pypy3\envs\pt28_rc1\python.exe
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('C:\\libohao\\pt28_rc1\\pytorch\\third_party\\torch-xpu-ops\\test\\xpu\\.hypothesis\\examples')
configfile: pytest.ini
plugins: hypothesis-5.35.1, cpp-2.3.0, flakefinder-1.1.0, rerunfailures-14.0, subtests-0.13.1, xdist-3.3.1, xdoctest-1.1.0
collected 1 item

nn\test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_MaxUnpool_index_errors_case2_xpu FAILED                 [100%]

====================================================== FAILURES =======================================================
__________________________ TestPoolingNNDeviceTypeXPU.test_MaxUnpool_index_errors_case2_xpu ___________________________
Traceback (most recent call last):
  File "C:\pt28_rc1\pytorch\third_party\torch-xpu-ops\test\xpu\nn\test_pooling_xpu.py", line 329, in _test_MaxUnpool_index_errors
    self.assertIn(error_msg, output, "The expected error was not found")
  File "C:\Users\kf01\miniforge-pypy3\envs\pt28_rc1\lib\unittest\case.py", line 1112, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\kf01\miniforge-pypy3\envs\pt28_rc1\lib\unittest\case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: 'Assertion `maxind >= 0 && maxind < outputImageSize` failed' not found in '\nAssertHandler::printMessage\n' : The expected error was not found

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python ..\..\test\nn\test_pooling.py TestPoolingNNDeviceTypeXPU.test_MaxUnpool_index_errors_case2_xpu

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
=============================================== short test summary info ===============================================
FAILED nn\test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_MaxUnpool_index_errors_case2_xpu - AssertionError: 'Assertion `maxind >= 0 && maxind < outputImageSize` failed' not found in '\nAssertHandler::printMe...
================================================== 1 failed in 8.25s ==================================================
```

ENV Info
```
pytorch-triton-xpu        3.4.0                    pypi_0    pypi
torch                     2.8.0+xpu                pypi_0    pypi
torchaudio                2.8.0a0+4e94321          pypi_0    pypi
torchvision               0.22.0a0+966da7e          pypi_0    pypi

triton commit: 3a9419c8bb6a98dd3e3cd473c36691fb4abeae40
pytorch commit:  03eb1e40f9ddf09cb9eef86ace74332e87f11a79 (HEAD, tag: v2.8.0-rc2)

```

**Comment by chuanqi129** [comment]
@chunhuanMeng please update status and create ticket to driver team

**Comment by xuhancn** [comment]
Check internal jira, this assert issue still not fix in DLE 2026.2, keep watching.
