### ISSUE TITLE
jit compare failed on LNL Windows.

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#1172]
### 🐛 Describe the bug

Got this error on LNL Windows with 1202 wheel. 

_______________________________________ TestAutograd.test_multi_grad_all_hooks ________________________________________
Traceback (most recent call last):
  File "c:\Users\dcai01\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\test_autograd.py", line 10004, in test_multi_grad_all_hooks
    module = load_inline(
  File "C:\Users\dcai01\.conda\envs\daisy\lib\site-packages\torch\testing\_internal\common_utils.py", line 5549, in load_inline
    return cpp_extension.load_inline(*args, **kwargs)
  File "C:\Users\dcai01\.conda\envs\daisy\lib\site-packages\torch\utils\cpp_extension.py", line 1690, in load_inline
    return _jit_compile(
  File "C:\Users\dcai01\.conda\envs\daisy\lib\site-packages\torch\utils\cpp_extension.py", line 1765, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\dcai01\.conda\envs\daisy\lib\site-packages\torch\utils\cpp_extension.py", line 1864, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\dcai01\.conda\envs\daisy\lib\site-packages\torch\utils\cpp_extension.py", line 2301, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\dcai01\.conda\envs\daisy\lib\site-packages\torch\utils\cpp_extension.py", line 2437, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\dcai01\.conda\envs\daisy\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\dcai01\.conda\envs\daisy\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
------------------------------------------------ Captured stderr call -------------------------------------------------
Using C:\Users\dcai01\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cpu as PyTorch extensions root...
C:\Users\dcai01\.conda\envs\daisy\lib\site-packages\torch\utils\cpp_extension.py:414: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Emitting ninja build file C:\Users\dcai01\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cpu\test_multigrad_all_hooks\build.ninja...
=============================================== short test summary info ===============================================
FAILED test_autograd_xpu.py::TestAutograd::test_multi_grad_all_hooks - subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
===================================== 1 failed, 1 passed, 631 deselected in 3.56s =====================================

### Versions

1202 wheel.

**Comment by daisyden** [comment]
After set "VS2022INSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools" it can pass.
