### ISSUE TITLE
test_rnn_backward_to_input_but_not_parameters_xpu failed

### ISSUE THREAD

**Issue by Stonepia** [intel/torch-xpu-ops#1192]
### 🐛 Describe the bug

Seems that we are running a wrong op.

```
PYTORCH_TEST_WITH_SLOW=1 python test\test_autograd.py TestAutogradDeviceTypeXPU.test_rnn_backward_to_input_but_not_parameters_xpu
```

```
_ TestAutogradDeviceTypeXPU.test_rnn_backward_to_input_but_not_parameters_xpu _
Traceback (most recent call last):
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_utils.py", line 3099, in wrapper
    method(*args, **kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 480, in instantiated_test
    raise rte
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 460, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 1409, in only_fn
    return fn(slf, *args, **kwargs)
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\test_autograd.py", line 11669, in test_rnn_backward_to_input_but_not_parameters
    out, _ = l(s)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\nn\modules\rnn.py", line 1122, in forward
    result = _VF.lstm(
NotImplementedError: Could not run 'aten::_thnn_fused_lstm_cell' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_thnn_fused_lstm_cell' is only available for these backends: [XPU, Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastXPU, AutocastMPS, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

XPU: registered at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\xpu\ATen\RegisterXPU.cpp:45384 [backend fallback]
Meta: registered at /dev/null:241 [kernel]
```

### Versions

Machine: LNL windows 11
PyTorch version: https://github.com/pytorch/pytorch/tree/90b7dcf2c5ee13b892701822f2abbc0e64f5584d
Install command: pip install --pre torch==2.6.0.dev20241202+xpu torchvision==0.20.0.dev20241202+xpu torchaudio==2.5.0.dev20241202+xpu --index-url https://download.pytorch.org/whl/nightly/xpu
torch-xpu-ops commit: https://github.com/intel/torch-xpu-ops/commit/bf4bab1ffffd84e5f747f65a17e08ee2fe633102

**Comment by Stonepia** [comment]
This is fixed by PR https://github.com/intel/torch-xpu-ops/pull/926
