### ISSUE TITLE
Need to skip CUDA tests

### ISSUE THREAD

**Issue by Stonepia** [intel/torch-xpu-ops#1196]
### 🐛 Describe the bug

XPU does not support FP8 tests for now. We need to skip them.

```
PYTORCH_TEST_WITH_SLOW=1 python test\test_matmul_cuda.py TestFP8MatmulCudaXPU.test_zero_dim_tensorwise_which_dim_zero_0_use_torch_compile_False_xpu
PYTORCH_TEST_WITH_SLOW=1 python test\test_matmul_cuda.py TestFP8MatmulCudaXPU.test_zero_dim_tensorwise_which_dim_zero_0_use_torch_compile_True_xpu
PYTORCH_TEST_WITH_SLOW=1 python test\test_matmul_cuda.py TestFP8MatmulCudaXPU.test_zero_dim_tensorwise_which_dim_zero_1_use_torch_compile_False_xpu
PYTORCH_TEST_WITH_SLOW=1 python test\test_matmul_cuda.py TestFP8MatmulCudaXPU.test_zero_dim_tensorwise_which_dim_zero_1_use_torch_compile_True_xpu
PYTORCH_TEST_WITH_SLOW=1 python test\test_matmul_cuda.py TestFP8MatmulCudaXPU.test_zero_dim_tensorwise_which_dim_zero_2_use_torch_compile_False_xpu
PYTORCH_TEST_WITH_SLOW=1 python test\test_matmul_cuda.py TestFP8MatmulCudaXPU.test_zero_dim_tensorwise_which_dim_zero_2_use_torch_compile_True_xpu
```

A typical error msg would be like:

```
_ TestFP8MatmulCudaXPU.test_zero_dim_tensorwise_which_dim_zero_2_use_torch_compile_True_xpu _
Traceback (most recent call last):
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_utils.py", line 3099, in wrapper
    method(*args, **kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 460, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\test_matmul_cuda.py", line 718, in test_zero_dim_tensorwise
    x_fp8 = torch.zeros(M, K, device=device).to(x_dtype)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### Versions

Machine: LNL windows 11
PyTorch version: https://github.com/pytorch/pytorch/tree/90b7dcf2c5ee13b892701822f2abbc0e64f5584d
Install command: pip install --pre torch==2.6.0.dev20241202+xpu torchvision==0.20.0.dev20241202+xpu torchaudio==2.5.0.dev20241202+xpu --index-url https://download.pytorch.org/whl/nightly/xpu
torch-xpu-ops commit: https://github.com/intel/torch-xpu-ops/commit/bf4bab1ffffd84e5f747f65a17e08ee2fe633102

**Comment by Stonepia** [comment]
This issue should have been fixed with PR https://github.com/intel/torch-xpu-ops/pull/1123
