### ISSUE TITLE
`test_learnable_forward_per_channel_cpu_xpu` AssertionError: False is not true

### ISSUE THREAD

**Issue by Stonepia** [intel/torch-xpu-ops#1197]
### 🐛 Describe the bug

When running the following test:

```
PYTORCH_TEST_WITH_SLOW=1 python test\quantization\core\test_workflow_ops.py TestFakeQuantizeOpsXPU.test_learnable_forward_per_channel_cpu_xpu
```

```
Traceback (most recent call last):
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_utils.py", line 3099, in wrapper
    method(*args, **kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 460, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\quantization/core\test_workflow_ops.py", line 807, in test_learnable_forward_per_channel_cpu
    qparams=hu.qparams(dtypes=torch.quint8)))
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\hypothesis\core.py", line 1758, in wrapped_test
    raise the_error_hypothesis_found
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\quantization/core\test_workflow_ops.py", line 815, in test_learnable_forward_per_channel_cpu
    self._test_learnable_forward_per_channel(
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\quantization/core\test_workflow_ops.py", line 802, in _test_learnable_forward_per_channel
    self.assertTrue(
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Expected kernel forward function to have results match the reference forward function
```

Seems that this is an accuracy issue. We need to compare the result with CUDA as well.

### Versions

Machine: LNL windows 11
PyTorch version: https://github.com/pytorch/pytorch/tree/90b7dcf2c5ee13b892701822f2abbc0e64f5584d
Install command: pip install --pre torch==2.6.0.dev20241202+xpu torchvision==0.20.0.dev20241202+xpu torchaudio==2.5.0.dev20241202+xpu --index-url https://download.pytorch.org/whl/nightly/xpu
torch-xpu-ops commit: https://github.com/intel/torch-xpu-ops/commit/bf4bab1ffffd84e5f747f65a17e08ee2fe633102

**Comment by Stonepia** [comment]
According to Daisy, this issue should be related to the environment. After correctly setup the env of pip packages, it should pass.
