### ISSUE TITLE
UT dtype mismatch for `pow` op

### ISSUE THREAD

**Issue by Stonepia** [intel/torch-xpu-ops#1198]
### 🐛 Describe the bug

We get the dtype mismatch for the `pow` op because the cast is failed. From the msg, seems that there should be a type conversion but failed.

```
PYTORCH_TEST_WITH_SLOW=1 python test\test_binary_ufuncs.py TestBinaryUfuncsXPU.test_long_tensor_pow_floats_xpu
```

```
RuntimeError: result type Float can't be cast to the desired output type Long

Traceback (most recent call last):
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_utils.py", line 3099, in wrapper
    method(*args, **kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 460, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\test_binary_ufuncs.py", line 1638, in test_long_tensor_pow_floats
    self._test_pow(tensor, pow)
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\test_binary_ufuncs_xpu.py", line 66, in _test_pow
    self.assertRaisesRegex(
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_utils.py", line 4065, in assertRaisesRegex
    return super().assertRaisesRegex(expected_exception, expected_regex, *args, **kwargs)
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 1291, in assertRaisesRegex
    return context.handle('assertRaisesRegex', args, kwargs)
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 200, in handle
    with self:
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 239, in __exit__
    self._raiseFailure('"{}" does not match "{}"'.format(
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 163, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: "Found dtype \w+ but expected \w+" does not match "result type Float can't be cast to the desired output type Long"
```

```
PYTORCH_TEST_WITH_SLOW=1 python test\test_binary_ufuncs.py TestBinaryUfuncsXPU.test_cuda_tensor_pow_scalar_tensor_xpu
```

```
Traceback (most recent call last):
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_utils.py", line 3099, in wrapper
    method(*args, **kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 460, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 1409, in only_fn
    return fn(slf, *args, **kwargs)
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\test_binary_ufuncs.py", line 1671, in test_cuda_tensor_pow_scalar_tensor
    self._test_pow(base, exp)
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\test_binary_ufuncs_xpu.py", line 63, in _test_pow
    self.assertEqual(actual, expected)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_utils.py", line 4007, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: The values for attribute 'dtype' do not match: torch.float32 != torch.float64.

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test\test_binary_ufuncs.py TestBinaryUfuncsXPU.test_cuda_tensor_pow_scalar_tensor_xpu
```

### Versions

Machine: LNL windows 11
PyTorch version: https://github.com/pytorch/pytorch/tree/90b7dcf2c5ee13b892701822f2abbc0e64f5584d
Install command: pip install --pre torch==2.6.0.dev20241202+xpu torchvision==0.20.0.dev20241202+xpu torchaudio==2.5.0.dev20241202+xpu --index-url https://download.pytorch.org/whl/nightly/xpu
torch-xpu-ops commit: https://github.com/intel/torch-xpu-ops/commit/bf4bab1ffffd84e5f747f65a17e08ee2fe633102

**Comment by Stonepia** [comment]
According to Daisy, this issue should be related to the environment. After correctly setup the env of pip packages, it should pass.
