### ISSUE TITLE
test_block_diag_scipy_xpu failed with dtype mismatch

### ISSUE THREAD

**Issue by Stonepia** [intel/torch-xpu-ops#1199]
### 🐛 Describe the bug

Seems that there should be a dtype conversion but we didn't do it:

```
PYTORCH_TEST_WITH_SLOW=1 python test\xpu\test_tensor_creation_ops_xpu.py TestTensorCreationXPU.test_block_diag_scipy_xpu
```

We get the following error:

```
Traceback (most recent call last):
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\sdp\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_utils.py", line 3099, in wrapper
    method(*args, **kwargs)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 460, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\pt26_ww48\pytorch\third_party\torch-xpu-ops\test\xpu\test_tensor_creation_ops_xpu.py", line 408, in test_block_diag_scipy
    self.assertEqual(scipy_result.dtype, scipy_type)
  File "C:\Users\sdp\pt26_ww48_virtual_env\lib\site-packages\torch\testing\_internal\common_utils.py", line 4007, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Object comparison failed: torch.int64 != torch.int32
```

### Versions

Machine: LNL windows 11
PyTorch version: https://github.com/pytorch/pytorch/tree/90b7dcf2c5ee13b892701822f2abbc0e64f5584d
Install command: pip install --pre torch==2.6.0.dev20241202+xpu torchvision==0.20.0.dev20241202+xpu torchaudio==2.5.0.dev20241202+xpu --index-url https://download.pytorch.org/whl/nightly/xpu
torch-xpu-ops commit: https://github.com/intel/torch-xpu-ops/commit/bf4bab1ffffd84e5f747f65a17e08ee2fe633102

**Comment by Stonepia** [comment]
According to Daisy, this issue should be related to the environment. After correctly setup the env of pip packages, it should pass.
