### ISSUE TITLE
[E2E] Torchbench models ImportError cached_download from huggingface_hub

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#1219]
### 🐛 Describe the bug

from huggingface_hub import cached_download
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/global/panfs01/users/mengfeil/miniforge3/envs/test/lib/python3.10/site-packages/huggingface_hub/__init__.py)

xpu  train stable_diffusion_text_encoder      
Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 4886, in run
    ) = runner.load_model(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 246, in load_model
    module = importlib.import_module(c)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/stable_diffusion_text_encoder/__init__.py", line 11, in <module>
    from diffusers import StableDiffusionPipeline, EulerDiscreteScheduler
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/huggingface_hub/__init__.py)

### Versions

huggingface-hub==0.26.0

**Comment by mengfei25** [comment]
Fixed in https://github.com/intel/torch-xpu-ops/pull/1218

**Comment by mengfei25** [comment]
Use pytorch pinned torchbench as CUDA and should be fixed in https://github.com/intel/torch-xpu-ops/pull/1226
