### ISSUE TITLE
[E2E] Torchbench torchrec_dlrm amp inference accuracy failed

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#1221]
### 🐛 Describe the bug

python benchmarks/dynamo/torchbench.py --accuracy --amp --amp-dtype float16 -d xpu -n10 --inference  --only torchrec_dlrm  --backend=inductor
```bash
xpu  eval  torchrec_dlrm                      
ERROR:common:
Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 3095, in check_accuracy
    new_result = optimized_model_iter_fn(model_copy, example_inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 576, in _fn
    return fn(*args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 2786, in run_n_iterations
    def run_n_iterations(self, mod, inputs):
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 751, in _fn
    return fn(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1186, in forward
    return compiled_fn(full_args)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 322, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 126, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 671, in inner_fn
    outs = compiled_fn(args)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 489, in wrapper
    return compiled_fn(runtime_args)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/output_code.py", line 465, in __call__
    return self.current_callable(inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/utils.py", line 2186, in run
    return model(new_inputs)
  File "/tmp/tmpr_qbdtso/lg/clgfoxqdtecedwclatggeagcrpitieaxizihdimxzd2wppd3fjkx.py", line 1411, in call
    extern_kernels.addmm(arg87_1, buf171, reinterpret_tensor(buf172, (512, 1728), (1, 512), 0), alpha=1, beta=1, out=buf173)
RuntimeError: self and mat2 must have the same dtype, but got Float and BFloat16
TorchDynamo optimized model failed to run because of following error
fail_to_run
```

### Versions

env:
python: 3.10
XPU_OPS: https://github.com/intel/torch-xpu-ops/commit/9ed0a1aed5e9735e26afb7330688e85299bbc589
TRITON_COMMIT_ID: e98b6fcb8df5b44eb0d0addb6767c573d37ba024
TORCH_COMMIT_ID: 4f8b7c4272db521f7ffc4070ce1bdece513d1183
TORCHBENCH_COMMIT_ID: 03cde49eba0580ed17f9ae2250832fd8af4ed756
TORCHVISION_COMMIT_ID: d23a6e1664d20707c11781299611436e1f0c104f
TORCHAUDIO_COMMIT_ID: a6b0a140cc13216975e8922093459019537bb80a
TRANSFORMERS_VERSION: 243e186efbf7fb93328dd6b34927a4e8c8f24395
TIMM_COMMIT_ID: ac3470188b914c5d7a5058a7e28b9eb685a62427
DRIVER_VERSION: 1.23.10.49.231129.50
KERNEL_VERSION: 5.15.0-73-generic https://github.com/intel/torch-xpu-ops/pull/80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023
BUNDLE_VERSION: 2025.0.1.20241113
OS_PRETTY_NAME: Ubuntu 22.04.2 LTS
GCC_VERSION: 11

**Comment by chuanqi129** [comment]
@mengfei25 is it a regression or not?

**Comment by mengfei25** [comment]
Regression, 2.5 is passed

**Comment by jianyizh** [comment]
same as https://github.com/intel/torch-xpu-ops/issues/719

**Comment by jianyizh** [comment]
Use #1577 to track
