### ISSUE TITLE
[E2E] Sam_fast NotImplementedError: The operator 'customflash::custom_flash_aligned' is not currently implemented for the XPU device

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#1234]
### 🐛 Describe the bug

CUDA is passed recently [sam_fast cuda](https://hud.pytorch.org/benchmark/torchbench/inductor_no_cudagraphs?dashboard=torchinductor&startTime=Mon%2C%2023%20Dec%202024%2007%3A01%3A11%20GMT&stopTime=Mon%2C%2030%20Dec%202024%2007%3A01%3A11%20GMT&granularity=hour&mode=inference&dtype=bfloat16&deviceName=cuda%20(a100)&lBranch=main&lCommit=cf0b72c4ab960a847758132cc501cf793926e070&rBranch=main&rCommit=cf0b72c4ab960a847758132cc501cf793926e070)
```bash
python benchmarks/dynamo/torchbench.py --accuracy --bfloat16 -d xpu -n10 --inference  --only sam_fast  --backend=inductor
xpu  eval  sam_fast                           
Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 2738, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 451, in forward_pass
    return mod(*inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/segment_anything_fast/modeling/sam.py", line 98, in forward
    image_embeddings = self.image_encoder(input_images)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 573, in _fn
    return fn(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/segment_anything_fast/modeling/image_encoder.py", line 107, in forward
    def forward(self, x: torch.Tensor) -> torch.Tensor:
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 744, in _fn
    return fn(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1184, in forward
    return compiled_fn(full_args)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 323, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 126, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 672, in inner_fn
    outs = compiled_fn(args)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 490, in wrapper
    return compiled_fn(runtime_args)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/output_code.py", line 466, in __call__
    return self.current_callable(inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/utils.py", line 2128, in run
    return model(new_inputs)
  File "/tmp/tmp3260uo4t/zq/czqs324zgqc3xehfmnal7nwn5bjifiuw42payisixvlunak5cxtp.py", line 4432, in call
    buf288 = torch.ops.customflash.custom_flash_aligned.default(buf284, buf285, buf286, buf287, 0.11180339887498948)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_ops.py", line 723, in __call__
    return self._op(*args, **kwargs)
NotImplementedError: The operator 'customflash::custom_flash_aligned' is not currently implemented for the XPU device. Please open a feature on https://github.com/intel/torch-xpu-ops/issues. You can set the environment variable `PYTORCH_ENABLE_XPU_FALLBACK=1` to use the CPU implementation as a fallback for XPU unimplemented operators. WARNING: this will bring unexpected performance compared with running natively on XPU.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 4873, in run
    ) = runner.load_model(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 372, in load_model
    self.validate_model(model, example_inputs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 2740, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
```

### Versions

Device PVC 1100
OS Ubuntu 22.04 LTS
Driver 803.61
Torch release/2.6 (31b520a59915990a9ea2d1f4c1d90a18a3a90dfe)
Torch-xpu-ops release/2.6 (https://github.com/intel/torch-xpu-ops/commit/214f33b9d969930a18656a82b5c5d8da53cdcb8e)
Triton e98b6fcb8df5b44eb0d0addb6767c573d37ba024
Transformers 243e186efbf7fb93328dd6b34927a4e8c8f24395
Torchvision d23a6e1664d20707c11781299611436e1f0c104f
Torchaudio 332760d4b300f00a0d862e3cfe1495db3b1a14f9
Torchbench 03cde49eba0580ed17f9ae2250832fd8af4ed756
Timms ac3470188b914c5d7a5058a7e28b9eb685a62427
Bundle 2025.0.1.20241113

**Comment by mengfei25** [comment]
Same as https://github.com/intel/torch-xpu-ops/issues/714

**Comment by Stonepia** [comment]
Close as duplicate.
