### ISSUE TITLE
[MTL Windows] test_embedding_max_norm_device_xpu_float32 assert error

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#1235]
### 🐛 Describe the bug

With nightly build 20241230 on Windows MLT:

FAILED nn\test_embedding_xpu.py::TestEmbeddingNNDeviceTypeXPU::test_embedding_max_norm_device_xpu_float32

___ TestEmbeddingNNDeviceTypeXPU.test_embedding_max_norm_device_xpu_float32 ___
Traceback (most recent call last):
  File "C:\Users\gta\penghuic\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\nn\test_embedding.py", line 764, in test_embedding_max_norm_device
    self.assertTrue(output.data.norm(p=2, dim=1).le(1).all())
  File "C:\Users\gta\Miniforge3\envs\ut-py310\lib\unittest\case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: tensor(False, device='xpu:0') is not true

To execute this test, run the following from the base repo dir:
    python test\nn\test_embedding.py TestEmbeddingNNDeviceTypeXPU.test_embedding_max_norm_device_xpu_float32

### Versions

With nightly build 20241230 on Windows MLT

**Comment by chuanqi129** [comment]
Close it due to MTL windows is low priority
