### ISSUE TITLE
[MLT Windows] multihead_attention float16 got accuracy issue

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#1237]
### 🐛 Describe the bug

FAILED test_native_mha_xpu.py::TestMHADeviceTypeXPU::test_native_multihead_attention_xpu_float16
================================== FAILURES ===================================
______ TestMHADeviceTypeXPU.test_native_multihead_attention_xpu_float16 _______
Traceback (most recent call last):
  File "C:\Users\gta\penghuic\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\test_native_mha.py", line 323, in test_native_multihead_attention
    self._test_multihead_attention_impl(
  File "C:\Users\gta\penghuic\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\test_native_mha.py", line 256, in _test_multihead_attention_impl
    torch.testing.assert_close(ypt, ynpt.to(torch.float32), atol=1e-3, rtol=1e-3)
  File "C:\Users\gta\Miniforge3\envs\ut-py310\lib\site-packages\torch\testing\_comparison.py", line 1530, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 416 / 8192 (5.1%)
Greatest absolute difference: 0.0026940107345581055 at index (2, 7, 62) (up to 0.001 allowed)
Greatest relative difference: 10.974992752075195 at index (10, 4, 51) (up to 0.001 allowed)

To execute this test, run the following from the base repo dir:
    python test\test_native_mha.py TestMHADeviceTypeXPU.test_native_multihead_attention_xpu_float16

FAILED test_native_mha_xpu.py::TestMHADeviceTypeXPU::test_native_multihead_encoder_decoder_attention_xpu_float16

================================== FAILURES ===================================
_ TestMHADeviceTypeXPU.test_native_multihead_encoder_decoder_attention_xpu_float16 _
Traceback (most recent call last):
  File "C:\Users\gta\penghuic\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\test_native_mha.py", line 309, in test_native_multihead_encoder_decoder_attention
    self._test_multihead_attention_impl(
  File "C:\Users\gta\penghuic\pytorch\third_party\torch-xpu-ops\test\xpu\../../../../test\test_native_mha.py", line 256, in _test_multihead_attention_impl
    torch.testing.assert_close(ypt, ynpt.to(torch.float32), atol=1e-3, rtol=1e-3)
  File "C:\Users\gta\Miniforge3\envs\ut-py310\lib\site-packages\torch\testing\_comparison.py", line 1530, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 454 / 8192 (5.5%)
Greatest absolute difference: 0.0034734010696411133 at index (1, 3, 48) (up to 0.001 allowed)
Greatest relative difference: 1.2274675369262695 at index (1, 6, 26) (up to 0.001 allowed)

To execute this test, run the following from the base repo dir:
    python test\test_native_mha.py TestMHADeviceTypeXPU.test_native_multihead_encoder_decoder_attention_xpu_float16

### Versions

nightly 20241230

**Comment by libohao1201** [comment]
This case passed with the latest driver 6647 + 0309 nightly torch whl.

```
============================= test session starts =============================
platform win32 -- Python 3.10.16, pytest-7.3.2, pluggy-1.5.0 -- C:\Users\Administrator\miniforge3\envs\mtl_ut_verify\python.exe
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('C:\\liboahoa\\pytorch\\third_party\\torch-xpu-ops\\test\\xpu\\.hypothesis\\examples')
rootdir: C:\liboahoa\pytorch
configfile: pytest.ini
plugins: hypothesis-5.35.1, cpp-2.3.0, flakefinder-1.1.0, rerunfailures-14.0, subtests-0.13.1, xdist-3.3.1, xdoctest-1.1.0
collecting ... collected 1 item

test_native_mha_xpu.py::TestMHADeviceTypeXPU::test_native_multihead_attention_xpu_float16 PASSED [100%]

============================= 1 passed in 25.80s ==============================
```
