### ISSUE TITLE
Support  deterministic flag in torch.backends.mkldnn.flags

### ISSUE THREAD

**Issue by PenghuiCheng** [intel/torch-xpu-ops#348]
### 🚀 The feature, motivation and pitch

command:
```python
pytest -v test/xpu/nn/test_convolution_xpu.py::TestConvolutionNNDeviceTypeXPU::test_conv_double_backward_xpu_float64
```
log:
```
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/ph_UT_test/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/gta/miniconda3/envs/ph_UT_test/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/home/gta/miniconda3/envs/ph_UT_test/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/gta/penghuic/pytorch_stock/torch/testing/_internal/common_utils.py", line 2763, in wrapper
    method(*args, **kwargs)
  File "/home/gta/penghuic/pytorch_stock/torch/testing/_internal/common_device_type.py", line 419, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/penghuic/pytorch_stock/third_party/torch-xpu-ops/test/xpu/nn/test_convolution_xpu.py", line 916, in conv_double_backward
    with torch.backends.mkldnn.flags(enabled=True, deterministic=True):
  File "/home/gta/miniconda3/envs/ph_UT_test/lib/python3.9/contextlib.py", line 263, in helper
    return _GeneratorContextManager(func, args, kwds)
  File "/home/gta/miniconda3/envs/ph_UT_test/lib/python3.9/contextlib.py", line 87, in __init__
    self.gen = func(*args, **kwds)
TypeError: flags() got an unexpected keyword argument 'deterministic'
```

**Comment by PenghuiCheng** [comment]
Log:
[convolution.log](https://github.com/intel/torch-xpu-ops/files/15477549/convolution.log)

**Comment by PenghuiCheng** [comment]
1~4, are fixed, and 5 is not in 2.5 plan.

**Comment by fengyuan14** [comment]
@ZhiweiYan-96 Please check the fifth issue, if it is a required new feature.

**Comment by ZhiweiYan-96** [comment]
> @ZhiweiYan-96 Please check the fifth issue, if it is a required new feature.

We already have a PR(https://github.com/pytorch/pytorch/pull/118064) for convolution ut, but not merged yet. I will follow this.
