### ISSUE TITLE
Moco NotImplementedError: xpu not supported

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#489]
### 🐛 Describe the bug

torchbench_amp_fp16_training
xpu  train moco
Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 4177, in run
    ) = runner.load_model(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 320, in load_model
    benchmark = benchmark_cls(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/util/model.py", line 39, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/moco/__init__.py", line 80, in __init__
    raise NotImplementedError(f"{device} not supported")
NotImplementedError: xpu not supported

model_fail_to_load

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/31c400195d63064940242220dc9100322d36bac4
pytorch: 0f81473d7b4a1bf09246410712df22541be7caf3 + PRs: 127277,129120
device: PVC 1100, 803.61, 0.5.1

**Comment by chuanqi129** [comment]
@weishi-deng does this issue still exist in latest torchbench? do we have plan to support it?

**Comment by weishi-deng** [comment]
This model requests the support for DDP models, the plan for support is still in progress.

**Comment by retonym** [comment]
The fix requires long term effort, not target to PT 2.6

**Comment by chuanqi129** [comment]
@mengfei25  check cuda status

**Comment by weishi-deng** [comment]
PR for model script: https://github.com/pytorch/benchmark/pull/2616
