### ISSUE TITLE
Timm_efficientdet NotImplementedError: The original model code forces the use of CUDA.

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#492]
### 🐛 Describe the bug

torchbench_amp_fp16_training
xpu  train timm_efficientdet
Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 4177, in run
    ) = runner.load_model(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 320, in load_model
    benchmark = benchmark_cls(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/util/model.py", line 39, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/timm_efficientdet/__init__.py", line 55, in __init__
    raise NotImplementedError("The original model code forces the use of CUDA.")
NotImplementedError: The original model code forces the use of CUDA.

model_fail_to_load

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/31c400195d63064940242220dc9100322d36bac4
pytorch: 0f81473d7b4a1bf09246410712df22541be7caf3 + PRs: 127277,129120
device: PVC 1100, 803.61, 0.5.1

**Comment by weishi-deng** [comment]
This model requests us to add xpu support for both the benchmark repo and third-party repo efficientdet-pytorch as it writes hard code with cuda like: (in https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/data/loader.py).

**Comment by weishi-deng** [comment]
PR https://github.com/pytorch/benchmark/pull/2374

**Comment by retonym** [comment]
The fix requires long term effort, not target to PT 2.6

**Comment by chuanqi129** [comment]
@chuanqi129 push the torchbench PR review and land
