### ISSUE TITLE
demucs RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#506]
### 🐛 Describe the bug

torchbench_bfloat16_training
xpu  train demucs                             
Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 2294, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 456, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1566, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1575, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/demucs/__init__.py", line 29, in forward
    return sources, self.model(mix)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1566, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1575, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/demucs/demucs/model.py", line 204, in forward
    x = encode(x)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1566, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1575, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1566, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1575, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 308, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 304, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 4177, in run
    ) = runner.load_model(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 380, in load_model
    self.validate_model(model, example_inputs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 2296, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run

loading model: 0it [00:00, ?it/s]
loading model: 0it [01:18, ?it/s]

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/31c400195d63064940242220dc9100322d36bac4
pytorch: 0f81473d7b4a1bf09246410712df22541be7caf3 + PRs: 127277,129120
device: PVC 1100, 803.61, 0.5.1

**Comment by retonym** [comment]
Both fp16 and bf16 have the problem

**Comment by retonym** [comment]
Same issue occurs in a100

**Comment by retonym** [comment]
Close the issue, since A100 also encounters the issue

**Comment by mengfei25** [comment]
A100 enabled this model recently

**Comment by jianyizh** [comment]
my local a100 also have the same error. @mengfei25 can you double check?

**Comment by mengfei25** [comment]
@jianyizh  Passed in [PyTorch HUD](https://hud.pytorch.org/benchmark/torchbench/inductor_no_cudagraphs?dashboard=torchinductor&startTime=Tue%2C%2003%20Jun%202025%2007%3A24%3A42%20GMT&stopTime=Tue%2C%2010%20Jun%202025%2007%3A24%3A42%20GMT&granularity=hour&mode=training&dtype=amp&deviceName=cuda%20(a100)&lBranch=main&lCommit=1339e88105cf72586d728d4f7e0d71b81e08d933&rBranch=main&rCommit=1339e88105cf72586d728d4f7e0d71b81e08d933)

**Comment by mengfei25** [comment]
cuda failed too
```
:~/mengfeil/pytorch$ python benchmarks/dynamo/torchbench.py --accuracy --float16 -d cuda -n10 --training  --only demucs --cold-start-latency --backend=inductor --output=/tmp/tmp.csv
loading model: 0it [00:01, ?it/s]
cuda train demucs
Traceback (most recent call last):
  File "/home/t/mengfeil/pytorch/benchmarks/dynamo/common.py", line 1898, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/home/t/mengfeil/pytorch/benchmarks/dynamo/torchbench.py", line 469, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/t/mengfeil/benchmark/torchbenchmark/models/demucs/__init__.py", line 33, in forward
    return sources, self.model(mix)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/t/mengfeil/benchmark/torchbenchmark/models/demucs/demucs/model.py", line 215, in forward
    x = encode(x)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 244, in forward
    input = module(input)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 371, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/t/mengfeil/myvenv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 366, in _conv_forward
    return F.conv1d(
RuntimeError: Input type (float) and bias type (c10::Half) should be the same

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/t/mengfeil/pytorch/benchmarks/dynamo/common.py", line 4004, in run
    ) = runner.load_model(
  File "/home/t/mengfeil/pytorch/benchmarks/dynamo/torchbench.py", line 381, in load_model
    self.validate_model(model, example_inputs)
  File "/home/t/mengfeil/pytorch/benchmarks/dynamo/common.py", line 1900, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run

```
