### ISSUE TITLE
Functorch_maml_omniglot fail_accuracy

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#510]
### 🐛 Describe the bug

torchbench_amp_bf16_training
xpu  train functorch_maml_omniglot            
E0626 14:52:43.796000 139708548429632 torch/_dynamo/utils.py:1478] RMSE (res-fp64): 0.00109, (ref-fp64): 0.00024 and shape=torch.Size([]). res.dtype: torch.float32, multiplier: 3.000000, tol: 0.001000
fail_accuracy

loading model: 0it [00:00, ?it/s]
loading model: 0it [00:02, ?it/s]

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/31c400195d63064940242220dc9100322d36bac4
pytorch: 0f81473d7b4a1bf09246410712df22541be7caf3 + PRs: 127277,129120
device: PVC 1100, 803.61, 0.5.1

**Comment by chuanqi129** [comment]
@retonym please help to assign this issue

**Comment by retonym** [comment]
Could not reproduce the accuracy failure in local pvc 1100.
From the error log, the absolute error is small, very likely caused by the even smaller ref error

**Comment by chuanqi129** [comment]
@mengfei25 please double check whether this issue always exist

**Comment by mengfei25** [comment]
still failed in latest weekly test

**Comment by retonym** [comment]
Thanks Mengfei, this model failure is expected. It can pass by slightly tuning tolerance

**Comment by chuanqi129** [comment]
@retonym will we submit a PR to change the tolerance

**Comment by retonym** [comment]
Sure, we will submit a PR to cover the tolerance change.

**Comment by retonym** [comment]
this datatype is not included in Meta dashboard, not target to PT 2.6

**Comment by mengfei25** [comment]
will failed with new issue
`Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 4886, in run
    ) = runner.load_model(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 312, in load_model
    benchmark = benchmark_cls(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/util/model.py", line 39, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/functorch_maml_omniglot/__init__.py", line 73, in __init__
    self.meta_inputs = torch.load(f'{root}/maml_omniglot/batch.pt')
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/serialization.py", line 1493, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, [1mdo those steps only if you trust the source of the checkpoint[0m. 
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy.core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([_reconstruct])` or the `torch.serialization.safe_globals([_reconstruct])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
`

**Comment by mengfei25** [comment]
Still in main branch

**Comment by Stonepia** [comment]
Close this issue as the parent tracker passed.
