### ISSUE TITLE
[E2E] Torchbench CUDA only models

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#712]
### 🐛 Describe the bug

- [x] `timm_efficientdet`
- [ ] `simple_gpt`
- [ ] `simple_gpt_tp_manual`

Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 4626, in run
    ) = runner.load_model(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 309, in load_model
    benchmark = benchmark_cls(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/util/model.py", line 39, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/timm_efficientdet/__init__.py", line 55, in __init__
    raise NotImplementedError("The original model code forces the use of CUDA.")
NotImplementedError: The original model code forces the use of CUDA.

model_fail_to_load

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/1d70431c072db889d9a47ea4956049fe340a426d
pytorch: d224857b3af5c9d5a3c7a48401475c09d90db296
device: pvc 1100, bundle: 0.5.3, driver: 803.61

**Comment by chuanqi129** [comment]
timm_efficientdet duplicate with https://github.com/intel/torch-xpu-ops/issues/492

**Comment by mengfei25** [comment]
simple_gpt on A100 are failed

**Comment by retonym** [comment]
timm_efficientdet is already tracked in https://github.com/intel/torch-xpu-ops/issues/492.
simple_gpt & simple_gpt_tp_manual are not within pytorch cuda dashboard.
