### ISSUE TITLE
[E2E] Torchbench accuracy XPU not supported

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#715]
### 🐛 Describe the bug

torchbench_amp_bf16_inference
- [ ] `moco`

Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 4626, in run
    ) = runner.load_model(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 309, in load_model
    benchmark = benchmark_cls(
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/util/model.py", line 39, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/moco/__init__.py", line 80, in __init__
    raise NotImplementedError(f"{device} not supported")
NotImplementedError: xpu not supported

model_fail_to_load

loading model: 0it [00:00, ?it/s]You are using a model of type moondream1 to instantiate a model of type phi. This is not supported for all configurations of models and can yield errors.

loading model: 0it [00:17, ?it/s]

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/1d70431c072db889d9a47ea4956049fe340a426d
pytorch: d224857b3af5c9d5a3c7a48401475c09d90db296
device: pvc 1100, bundle: 0.5.3, driver: 803.61

**Comment by mengfei25** [comment]
A100 pass

**Comment by chuanqi129** [comment]
TB model script issue, @weishi-deng will we check whether this model can be supported on xpu also?

**Comment by weishi-deng** [comment]
duplicated as https://github.com/intel/torch-xpu-ops/issues/489

**Comment by retonym** [comment]
close the issue for duplication
