### ISSUE TITLE
[E2E] Torchbench tacotron2 accuracy failed

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#717]
### 🐛 Describe the bug

torchbench_amp_bf16_inference
xpu  eval  tacotron2                          
W0803 04:28:41.161000 2371708 torch/_inductor/utils.py:1357] [3/0_1] DeviceCopy in input program
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0] Graph break from `Tensor.item()`, consider setting:
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0]     torch._dynamo.config.capture_scalar_outputs = True
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0] or:
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0]     env TORCHDYNAMO_CAPTURE_SCALAR_OUTPUTS=1
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0] to include these operations in the captured graph.
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0] 
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0] Graph break: from user code at:
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0]   File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/tacotron2/model.py", line 473, in torch_dynamo_resume_in_forward_at_467
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0]     memory, mask=~get_mask_from_lengths(memory_lengths)
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0]   File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/tacotron2/tacotron2_utils.py", line 10, in get_mask_from_lengths
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0]     max_len = torch.max(lengths).item()
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0] 
W0803 04:28:42.165000 2371708 torch/_dynamo/variables/tensor.py:776] [9/0] 
L0 build module failed. Log: 
ERROR:common:
Traceback (most recent call last):
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1437, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/backends/inductor.py", line 16, in inductor
    return compile_fx(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1488, in compile_fx
    return aot_autograd(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 69, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1019, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1008, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 429, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(flat_fn, flat_args, aot_config)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 730, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 178, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1327, in fw_compiler_base
    return _fw_compiler_base(model, example_inputs, is_inference)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1394, in _fw_compiler_base
    return inner_compile(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 457, in compile_fx_inner
    return _compile_fx_inner(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/repro/after_aot.py", line 85, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/debug.py", line 313, in inner
    return fn(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 446, in wrapper
    return fn(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 644, in _compile_fx_inner
    compiled_graph = FxGraphCache.load(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 1291, in load
    compiled_graph = compile_fx_fn(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 554, in codegen_and_compile
    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 855, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1844, in compile_to_fn
    return self.compile_to_module().call
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1770, in compile_to_module
    return self._compile_to_module()
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1798, in _compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 3228, in load_by_key_path
    mod = _reload_python_module(key, path)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/runtime/compile_tasks.py", line 45, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_sdp/gr/cgrwnkaegbo7urihdge5mqa7yhbjnwq3udwcq2wbuyy7757jbnfi.py", line 36611, in <module>
    async_compile.wait(globals())
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/async_compile.py", line 261, in wait
    scope[key] = result.result()
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 3683, in result
    self.kernel.precompile()
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 234, in precompile
    compiled_binary, launcher = self._precompile_config(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 442, in _precompile_config
    binary._init_handles()
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/triton/compiler/compiler.py", line 376, in _init_handles
    self.module, self.function, self.n_regs, self.n_spills = driver.active.utils.load_binary(
RuntimeError: Triton Error [ZE]: 0x70000004

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 2846, in check_accuracy
    new_result = optimized_model_iter_fn(model_copy, example_inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 464, in _fn
    return fn(*args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 2550, in run_n_iterations
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 439, in forward_pass
    return mod(*inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/tacotron2/model.py", line 577, in forward
    encoder_outputs = self.encoder(embedded_inputs, text_lengths)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/tacotron2/model.py", line 579, in torch_dynamo_resume_in_forward_at_577
    mel_outputs, gate_outputs, alignments = self.decoder(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/tacotron2/model.py", line 467, in forward
    decoder_input = self.get_go_frame(memory).unsqueeze(0)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/tacotron2/model.py", line 473, in torch_dynamo_resume_in_forward_at_467
    memory, mask=~get_mask_from_lengths(memory_lengths)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/tacotron2/model.py", line 472, in torch_dynamo_resume_in_forward_at_473
    self.initialize_decoder_states(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1224, in __call__
    return self._torchdynamo_orig_callable(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1025, in __call__
    result = self._inner_convert(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 514, in __call__
    return _compile(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 896, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 662, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_utils_internal.py", line 85, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 697, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 631, in transform
    tracer.run()
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2722, in run
    super().run()
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2913, in RETURN_VALUE
    self._return(inst)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2898, in _return
    self.output.compile_subgraph(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1133, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1360, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1407, in call_user_compiler
    return self._call_user_compiler(gm)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1456, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Triton Error [ZE]: 0x70000004

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

TorchDynamo optimized model failed to run because of following error
fail_to_run
accuracy            pass_rate=71.15%
calls_captured      gmean=0.00x mean=726.413x
unique_graphs       gmean=0.00x mean=1.894x
graph_breaks        gmean=0.00x mean=0.952x
unique_graph_breaks gmean=0.00x mean=0.269x
autograd_captures   gmean=0.00x mean=0.000x
autograd_compiles   gmean=0.00x mean=0.000x
cudagraph_skips     gmean=0.00x mean=1.606x

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/1d70431c072db889d9a47ea4956049fe340a426d
pytorch: d224857b3af5c9d5a3c7a48401475c09d90db296
device: pvc 1100, bundle: 0.5.3, driver: 803.61

**Comment by retonym** [comment]
low priority for not included in Meta PyTorch dashboard

**Comment by mengfei25** [comment]
A100 is also failed

**Comment by retonym** [comment]
close the issue, due to a100 also failed
