### ISSUE TITLE
[E2E] Torchbench tacotron2 amp_bf16 training accuracy failed

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#727]
### 🐛 Describe the bug

torchbench_amp_bf16_training
xpu  train tacotron2                          
W0803 05:40:15.849000 2621977 torch/_inductor/utils.py:1357] [5/0_1] DeviceCopy in input program
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0] Graph break from `Tensor.item()`, consider setting:
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0]     torch._dynamo.config.capture_scalar_outputs = True
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0] or:
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0]     env TORCHDYNAMO_CAPTURE_SCALAR_OUTPUTS=1
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0] to include these operations in the captured graph.
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0] 
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0] Graph break: from user code at:
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0]   File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/tacotron2/model.py", line 473, in torch_dynamo_resume_in_forward_at_467
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0]     memory, mask=~get_mask_from_lengths(memory_lengths)
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0]   File "/home/sdp/actions-runner/_work/torch-xpu-ops/benchmark/torchbenchmark/models/tacotron2/tacotron2_utils.py", line 10, in get_mask_from_lengths
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0]     max_len = torch.max(lengths).item()
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0] 
W0803 05:40:17.019000 2621977 torch/_dynamo/variables/tensor.py:776] [11/0] 
ERROR:common:
Traceback (most recent call last):
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 2846, in check_accuracy
    new_result = optimized_model_iter_fn(model_copy, example_inputs)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 464, in _fn
    return fn(*args, **kwargs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/common.py", line 2550, in run_n_iterations
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 442, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 443, in torch_dynamo_resume_in_forward_and_backward_pass_at_442
    self.optimizer_zero_grad(mod)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 448, in torch_dynamo_resume_in_forward_and_backward_pass_at_443
    pred = mod(*cloned_inputs)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 449, in torch_dynamo_resume_in_forward_and_backward_pass_at_448
    loss = self.compute_loss(pred)
  File "/home/sdp/actions-runner/_work/torch-xpu-ops/pytorch/benchmarks/dynamo/torchbench.py", line 450, in torch_dynamo_resume_in_forward_and_backward_pass_at_449
    self.grad_scaler.scale(loss).backward()
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/autograd/__init__.py", line 346, in backward
    _engine_run_backward(
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/autograd/graph.py", line 812, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/autograd/function.py", line 306, in apply
    return user_fn(self, *args)
  File "/home/sdp/miniforge3/envs/e2e_ci/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1721, in backward
    *ctx.saved_tensors,
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [XPUBFloat16Type [4, 80, 724]], which is output 0 of torch::autograd::CopyBackwards, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
TorchDynamo optimized model failed to run because of following error
fail_to_run
accuracy            pass_rate=52.88%
calls_captured      gmean=0.00x mean=447.154x
unique_graphs       gmean=0.00x mean=2.000x
graph_breaks        gmean=0.00x mean=3.519x
unique_graph_breaks gmean=0.00x mean=2.529x
autograd_captures   gmean=0.00x mean=0.000x
autograd_compiles   gmean=0.00x mean=0.000x
cudagraph_skips     gmean=0.00x mean=1.192x

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/1d70431c072db889d9a47ea4956049fe340a426d
pytorch: d224857b3af5c9d5a3c7a48401475c09d90db296
device: pvc 1100, bundle: 0.5.3, driver: 803.61

**Comment by retonym** [comment]
low priority for not included in Meta PyTorch dashboard

**Comment by mengfei25** [comment]
A100  is also failed.

**Comment by retonym** [comment]
close due to a100 also failed
