### ISSUE TITLE
Kenito profiler: UT failure after enable PTI (TestAutograd::test_profiler)

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#731]
### 🐛 Describe the bug

- [ ] TestAutograd::test_record_function   ------fixed
- [ ] TestAutograd::test_profiler

```
2024-08-08T06:02:04.0982790Z =================================== FAILURES ===================================
2024-08-08T06:02:04.0985298Z [31m[1m__________________________ TestAutograd.test_profiler __________________________[0m
2024-08-08T06:02:04.0985755Z Traceback (most recent call last):
2024-08-08T06:02:04.0986502Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_autograd.py", line 4603, in test_profiler
2024-08-08T06:02:04.0987176Z     with profile(use_kineto=kineto_available()) as p:
2024-08-08T06:02:04.0987850Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/autograd/profiler.py", line 315, in __enter__
2024-08-08T06:02:04.0988397Z     self._prepare_trace()
2024-08-08T06:02:04.0988976Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/autograd/profiler.py", line 322, in _prepare_trace
2024-08-08T06:02:04.0989570Z     _prepare_profiler(self.config(), self.kineto_activities)
2024-08-08T06:02:04.0990166Z RuntimeError: Fail to enable Kineto Profiler on XPU due to error code: 200
2024-08-08T06:02:04.0990450Z 
2024-08-08T06:02:04.0990618Z To execute this test, run the following from the base repo dir:
2024-08-08T06:02:04.0992197Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_autograd.py TestAutograd.test_profiler
2024-08-08T06:02:04.0992562Z 
2024-08-08T06:02:04.0992791Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-08-08T06:02:04.0993420Z [36m[1m=========================== short test summary info ============================[0m
2024-08-08T06:02:04.0996133Z [31mFAILED[0m test_autograd_xpu.py::[1mTestAutograd::test_profiler[0m - RuntimeError: Fail to enable Kineto Profiler on XPU due to error code: 200
```

### Versions

Latest PyTorch

**Comment by fengyuan14** [comment]
Should assign to Zejun, but he is not the member of the project so far.

**Comment by PenghuiCheng** [comment]
TestAutograd::test_profiler failure：AttributeError: module 'torch.xpu' has no attribute 'profiler。
