### ISSUE TITLE
new ut failures introduced by new pytorch

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#746]
### 🐛 Describe the bug

- [x] PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py TestModuleXPU.test_non_contiguous_tensors_nn_Conv3d_xpu_float32 - need to adjust tolerence
- [x] PYTORCH_TEST_WITH_SLOW=1 python test/test_dynamic_shapes.py TestSymNumberMagicMethods.test_method_fn_add_first_type_int_second_type_float
- [x] PYTORCH_TEST_WITH_SLOW=1 python test/test_dynamic_shapes.py TestSymNumberMagicMethods.test_method_fn_mul_first_type_int_second_type_float
- [x] PYTORCH_TEST_WITH_SLOW=1 python test/test_dynamic_shapes.py TestSymNumberMagicMethods.test_method_fn_sub_first_type_int_second_type_float

```
2024-08-12T01:30:41.2003975Z =================================== FAILURES ===================================
2024-08-12T01:30:41.2004503Z [31m[1m_______ TestModuleXPU.test_non_contiguous_tensors_nn_Conv3d_xpu_float32 ________[0m
2024-08-12T01:30:41.2004910Z Traceback (most recent call last):
2024-08-12T01:30:41.2010071Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_modules.py", line 434, in test_non_contiguous_tensors
2024-08-12T01:30:41.2010860Z     self.assertEqual(param_grad, default_param_grad)
2024-08-12T01:30:41.2011615Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3824, in assertEqual
2024-08-12T01:30:41.2012215Z     raise error_metas.pop()[0].to_error(
2024-08-12T01:30:41.2012572Z AssertionError: Tensor-likes are not close!
2024-08-12T01:30:41.2012786Z 
2024-08-12T01:30:41.2016850Z Mismatched elements: 1 / 540 (0.2%)
2024-08-12T01:30:41.2017647Z Greatest absolute difference: 1.52587890625e-05 at index (0, 1, 1, 1, 2) (up to 1e-05 allowed)
2024-08-12T01:30:41.2018299Z Greatest relative difference: 3.042357275262475e-05 at index (0, 1, 1, 1, 2) (up to 1e-05 allowed)
2024-08-12T01:30:41.2018644Z 
2024-08-12T01:30:41.2018934Z The failure occurred for item [0]
2024-08-12T01:30:41.2019191Z 
2024-08-12T01:30:41.2019354Z To execute this test, run the following from the base repo dir:
2024-08-12T01:30:41.2019931Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py TestModuleXPU.test_non_contiguous_tensors_nn_Conv3d_xpu_float32


2024-08-12T02:25:44.2104472Z =================================== FAILURES ===================================
2024-08-12T02:25:44.2105942Z [31m[1m_ TestSymNumberMagicMethods.test_method_fn_add_first_type_int_second_type_float _[0m
2024-08-12T02:25:44.2106518Z Traceback (most recent call last):
2024-08-12T02:25:44.2107261Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1244, in test_method
2024-08-12T02:25:44.2107940Z     self._do_test(fn, inp1, inp2, shape_env, is_unary_fn)
2024-08-12T02:25:44.2108669Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1072, in _do_test
2024-08-12T02:25:44.2109736Z     return self._do_test2(fn, inp1, inp2, shape_env, is_unary_fn)
2024-08-12T02:25:44.2110573Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1164, in _do_test2
2024-08-12T02:25:44.2111396Z     out = guard_fn(out)
2024-08-12T02:25:44.2112039Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1144, in guard_fn
2024-08-12T02:25:44.2112630Z     return guard_float(v)
2024-08-12T02:25:44.2113240Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 1030, in guard_float
2024-08-12T02:25:44.2113994Z     return a.node.guard_float("", 0)  # NB: uses Python backtrace
2024-08-12T02:25:44.2114689Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 439, in guard_float
2024-08-12T02:25:44.2115356Z     r = self.shape_env.evaluate_expr(
2024-08-12T02:25:44.2115999Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/recording.py", line 262, in wrapper
2024-08-12T02:25:44.2116748Z     return retlog(fn(*args, **kwargs))
2024-08-12T02:25:44.2117468Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5214, in evaluate_expr
2024-08-12T02:25:44.2118237Z     return self._evaluate_expr(orig_expr, hint, fx_node, expect_rational, size_oblivious, forcing_spec=forcing_spec)
2024-08-12T02:25:44.2119095Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5285, in _evaluate_expr
2024-08-12T02:25:44.2119708Z     assert orig_expr == hint, f"{orig_expr} != {hint}"
2024-08-12T02:25:44.2120007Z AssertionError: 0 != 0.0
2024-08-12T02:25:44.2120147Z 
2024-08-12T02:25:44.2120308Z To execute this test, run the following from the base repo dir:
2024-08-12T02:25:44.2120935Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_dynamic_shapes.py TestSymNumberMagicMethods.test_method_fn_add_first_type_int_second_type_float
2024-08-12T02:25:44.2121392Z 
2024-08-12T02:25:44.2121668Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-08-12T02:25:44.2122156Z ----------------------------- Captured stderr call -----------------------------
2024-08-12T02:25:44.2122894Z W0812 02:25:41.962000 1463677 torch/fx/experimental/symbolic_shapes.py:5216] failed during evaluate_expr(0, hint=0.0, expect_rational=False, size_oblivious=False, forcing_spec=False
2024-08-12T02:25:44.2123976Z E0812 02:25:41.962000 1463677 torch/fx/experimental/recording.py:298] failed while running evaluate_expr(*(0, 0.0), **{'fx_node': False, 'expect_rational': False})
2024-08-12T02:25:44.2124782Z [31m[1m_ TestSymNumberMagicMethods.test_method_fn_mul_first_type_int_second_type_float _[0m
2024-08-12T02:25:44.2125200Z Traceback (most recent call last):
2024-08-12T02:25:44.2125910Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1244, in test_method
2024-08-12T02:25:44.2126616Z     self._do_test(fn, inp1, inp2, shape_env, is_unary_fn)
2024-08-12T02:25:44.2127355Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1072, in _do_test
2024-08-12T02:25:44.2128008Z     return self._do_test2(fn, inp1, inp2, shape_env, is_unary_fn)
2024-08-12T02:25:44.2128755Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1164, in _do_test2
2024-08-12T02:25:44.2129338Z     out = guard_fn(out)
2024-08-12T02:25:44.2129956Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1144, in guard_fn
2024-08-12T02:25:44.2130668Z     return guard_float(v)
2024-08-12T02:25:44.2131303Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 1030, in guard_float
2024-08-12T02:25:44.2131959Z     return a.node.guard_float("", 0)  # NB: uses Python backtrace
2024-08-12T02:25:44.2132639Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 439, in guard_float
2024-08-12T02:25:44.2133194Z     r = self.shape_env.evaluate_expr(
2024-08-12T02:25:44.2133806Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/recording.py", line 262, in wrapper
2024-08-12T02:25:44.2134330Z     return retlog(fn(*args, **kwargs))
2024-08-12T02:25:44.2134979Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5214, in evaluate_expr
2024-08-12T02:25:44.2135805Z     return self._evaluate_expr(orig_expr, hint, fx_node, expect_rational, size_oblivious, forcing_spec=forcing_spec)
2024-08-12T02:25:44.2136662Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5285, in _evaluate_expr
2024-08-12T02:25:44.2137267Z     assert orig_expr == hint, f"{orig_expr} != {hint}"
2024-08-12T02:25:44.2137567Z AssertionError: 0 != 0.0
2024-08-12T02:25:44.2137703Z 
2024-08-12T02:25:44.2137872Z To execute this test, run the following from the base repo dir:
2024-08-12T02:25:44.2138490Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_dynamic_shapes.py TestSymNumberMagicMethods.test_method_fn_mul_first_type_int_second_type_float
2024-08-12T02:25:44.2138953Z 
2024-08-12T02:25:44.2139146Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-08-12T02:25:44.2139625Z ----------------------------- Captured stderr call -----------------------------
2024-08-12T02:25:44.2140355Z W0812 02:25:42.439000 1463677 torch/fx/experimental/symbolic_shapes.py:5216] failed during evaluate_expr(0, hint=0.0, expect_rational=False, size_oblivious=False, forcing_spec=False
2024-08-12T02:25:44.2141422Z E0812 02:25:42.439000 1463677 torch/fx/experimental/recording.py:298] failed while running evaluate_expr(*(0, 0.0), **{'fx_node': False, 'expect_rational': False})
2024-08-12T02:25:44.2142247Z [31m[1m_ TestSymNumberMagicMethods.test_method_fn_sub_first_type_int_second_type_float _[0m
2024-08-12T02:25:44.2142676Z Traceback (most recent call last):
2024-08-12T02:25:44.2143363Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1244, in test_method
2024-08-12T02:25:44.2144040Z     self._do_test(fn, inp1, inp2, shape_env, is_unary_fn)
2024-08-12T02:25:44.2144766Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1072, in _do_test
2024-08-12T02:25:44.2145433Z     return self._do_test2(fn, inp1, inp2, shape_env, is_unary_fn)
2024-08-12T02:25:44.2146177Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1164, in _do_test2
2024-08-12T02:25:44.2146783Z     out = guard_fn(out)
2024-08-12T02:25:44.2147421Z   File "/home/sdp/actions-runner-0/_work/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/../../../../test/test_dynamic_shapes.py", line 1144, in guard_fn
2024-08-12T02:25:44.2148010Z     return guard_float(v)
2024-08-12T02:25:44.2148621Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 1030, in guard_float
2024-08-12T02:25:44.2149269Z     return a.node.guard_float("", 0)  # NB: uses Python backtrace
2024-08-12T02:25:44.2149957Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 439, in guard_float
2024-08-12T02:25:44.2150511Z     r = self.shape_env.evaluate_expr(
2024-08-12T02:25:44.2151121Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/recording.py", line 262, in wrapper
2024-08-12T02:25:44.2151658Z     return retlog(fn(*args, **kwargs))
2024-08-12T02:25:44.2152308Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5214, in evaluate_expr
2024-08-12T02:25:44.2153080Z     return self._evaluate_expr(orig_expr, hint, fx_node, expect_rational, size_oblivious, forcing_spec=forcing_spec)
2024-08-12T02:25:44.2153937Z   File "/home/sdp/miniforge3/envs/xpu_op_0/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5285, in _evaluate_expr
2024-08-12T02:25:44.2154549Z     assert orig_expr == hint, f"{orig_expr} != {hint}"
2024-08-12T02:25:44.2154842Z AssertionError: 0 != 0.0
2024-08-12T02:25:44.2154980Z 
2024-08-12T02:25:44.2155139Z To execute this test, run the following from the base repo dir:
2024-08-12T02:25:44.2155822Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_dynamic_shapes.py TestSymNumberMagicMethods.test_method_fn_sub_first_type_int_second_type_float
2024-08-12T02:25:44.2156272Z 
2024-08-12T02:25:44.2156477Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-08-12T02:25:44.2156952Z ----------------------------- Captured stderr call -----------------------------
2024-08-12T02:25:44.2157683Z W0812 02:25:42.602000 1463677 torch/fx/experimental/symbolic_shapes.py:5216] failed during evaluate_expr(0, hint=0.0, expect_rational=False, size_oblivious=False, forcing_spec=False
2024-08-12T02:25:44.2158756Z E0812 02:25:42.603000 1463677 torch/fx/experimental/recording.py:298] failed while running evaluate_expr(*(0, 0.0), **{'fx_node': False, 'expect_rational': False})
2024-08-12T02:25:44.2159480Z [36m[1m=========================== short test summary info ============================[0m
2024-08-12T02:25:44.2160427Z [31mFAILED[0m test_dynamic_shapes_xpu.py::[1mTestSymNumberMagicMethods::test_method_fn_add_first_type_int_second_type_float[0m - AssertionError: 0 != 0.0
2024-08-12T02:25:44.2160919Z 
2024-08-12T02:25:44.2161085Z To execute this test, run the following from the base repo dir:
2024-08-12T02:25:44.2161741Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_dynamic_shapes.py TestSymNumberMagicMethods.test_method_fn_add_first_type_int_second_type_float
2024-08-12T02:25:44.2162193Z 
2024-08-12T02:25:44.2162400Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-08-12T02:25:44.2163167Z [31mFAILED[0m test_dynamic_shapes_xpu.py::[1mTestSymNumberMagicMethods::test_method_fn_mul_first_type_int_second_type_float[0m - AssertionError: 0 != 0.0
2024-08-12T02:25:44.2163647Z 
2024-08-12T02:25:44.2163805Z To execute this test, run the following from the base repo dir:
2024-08-12T02:25:44.2164430Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_dynamic_shapes.py TestSymNumberMagicMethods.test_method_fn_mul_first_type_int_second_type_float
2024-08-12T02:25:44.2164880Z 
2024-08-12T02:25:44.2165090Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-08-12T02:25:44.2165845Z [31mFAILED[0m test_dynamic_shapes_xpu.py::[1mTestSymNumberMagicMethods::test_method_fn_sub_first_type_int_second_type_float[0m - AssertionError: 0 != 0.0
2024-08-12T02:25:44.2167058Z 
2024-08-12T02:25:44.2167223Z To execute this test, run the following from the base repo dir:
2024-08-12T02:25:44.2167846Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_dynamic_shapes.py TestSymNumberMagicMethods.test_method_fn_sub_first_type_int_second_type_float

```

### Versions

```
PyTorch
2024-08-12T00:48:09.6655284Z commit 7f08b73980a9843acc0ccca9bb3daf95bc39fd3d
2024-08-12T00:48:09.6655734Z Author: PyTorch MergeBot <pytorchmergebot@users.noreply.github.com>
2024-08-12T00:48:09.6656105Z Date:   Sun Aug 11 23:33:37 2024 +0000
2024-08-12T00:48:09.6656287Z 
2024-08-12T00:48:09.6656490Z     Revert "[Memory Snapshot][Viz] Show event timestamps if collected (#132523)"
2024-08-12T00:48:09.6656843Z     
2024-08-12T00:48:09.6657080Z     This reverts commit 456909e5d350810e941290ee61c1dfc3315a9a69.

```

**Comment by daisyden** [comment]
Verified on pytorch commit 27c44c884e28c9378677fb295a528c36c429c3f7 and torch-xpu-ops commit 11f27e827fd9f4ef9e18a913612b6e32920bd632, the 4 cases are passed, the 1st one need to adjust tolerence.

**Comment by yuchengliu1** [comment]
test_non_contiguous_tensors_nn_Conv3d_xpu_float32 pass in #749
