### ISSUE TITLE
[E2E] [MTL] BF16 models failed with error Triton Error [ZE]: 0x70000004

### ISSUE THREAD

**Issue by Stonepia** [intel/torch-xpu-ops#750]
# Bug statement

Error message like 

```
L0 build module failed. Log:
error: bf conversion instruction not supported!
in kernel: 'triton_poi_fused__to_copy_2'
error: backend compiler failed build.

Traceback (most recent call last):
  File "/home/gta/actions-runner/actions-runner/_work/torch-xpu-ops/repro.py", line 34, in <module>
    async_compile.wait(globals())
  File "/opt/conda/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/async_compile.py", line 261, in wait
    scope[key] = result.result()
  File "/opt/conda/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 3745, in result
    self.kernel.precompile()
  File "/opt/conda/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 234, in precompile
    compiled_binary, launcher = self._precompile_config(
  File "/opt/conda/envs/e2e_ci/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 442, in _precompile_config
    binary._init_handles()
  File "/opt/conda/envs/e2e_ci/lib/python3.10/site-packages/triton/compiler/compiler.py", line 376, in _init_handles
    self.module, self.function, self.n_regs, self.n_spills = driver.active.utils.load_binary(
RuntimeError: Triton Error [ZE]: 0x70000004
```

# Tracking
This tracks issue in:
https://github.com/intel/intel-xpu-backend-for-triton/issues/1847

**Comment by chuanqi129** [comment]
@riverliuintel help to check triton code freeze data and make sure this fix is included

**Comment by Stonepia** [comment]
@mengfei25  FYI.

**Comment by Stonepia** [comment]
The issue is verified with latest triton release/2.5.0 branch, and it should work with PyTorch with commit id later than
https://github.com/pytorch/pytorch/commit/fbd020fce649ddb44bd9a578dabb5834c5d0f186

Close this issue as complete.
